# Generated by Django 4.2.2 on 2023-07-18 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reservacion', models.DateField()),
                ('tipo_reserva', models.CharField(max_length=20)),
                ('cantidad_personad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.usuario')),
            ],
        ),
    ]
