# Generated by Django 4.2.2 on 2023-07-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservacion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservacion',
            table='Reservacion',
        ),
    ]
