# Generated by Django 4.2.2 on 2023-07-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservacion_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservacion',
            old_name='cantidad_personad',
            new_name='cantidad_personas',
        ),
    ]
