# Generated by Django 4.2.2 on 2023-07-19 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservacion_reservado_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.usuario'),
        ),
    ]
